<a href="https://colab.research.google.com/github/Nidarshan619/pytorch-beginner/blob/master/DLinPytorch_Book/p1ch5/2_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline
import numpy as np
import torch
torch.set_printoptions(edgeitems=2)

In [2]:
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0,
                    3.0, -4.0, 6.0, 13.0, 21.0])
t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9,
                    33.9, 21.8, 48.4, 60.4, 68.4])
t_un = 0.1 * t_u

In [12]:
t_un.grad is None  # Within 10

True

In [3]:
def model(t_u, w, b):
    return w * t_u + b

In [4]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [5]:
params = torch.tensor([1.0, 0.0], requires_grad=True)

In [21]:
paramss = torch.tensor([0.1, 0.1], requires_grad=True)

In [23]:
  params = params - paramss
  params

tensor([ 0.6000, -0.4000], grad_fn=<SubBackward0>)

In [24]:
with torch.no_grad():
  params = params - paramss
params  

tensor([ 0.5000, -0.5000])

In [ ]:
params = torch.tensor([1.0, 0.0], requires_grad=True)

In [17]:
params.no_grad()

AttributeError: ignored

In [6]:
loss = loss_fn(model(t_u, *params), t_c)


In [8]:
print(params.grad)

None


In [11]:
#loss.backward()
print(params.grad)

tensor([4517.2969,   82.6000])


In [20]:
loss = loss_fn(model(t_u, *params), t_c)
loss.backward()

params.grad
params.grad is None

False

In [14]:
if params.grad is not None:
    params.grad.zero_()

In [19]:
params

tensor([1., 0.], requires_grad=True)

In [12]:
def training_loop(n_epochs, learning_rate, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        if params.grad is not None:  # <1>
            params.grad.zero_()
        
        t_p = model(t_u, *params) 
        loss = loss_fn(t_p, t_c)
        loss.backward()
        
        with torch.no_grad():  # <2>
            params -= learning_rate * params.grad

        if epoch % 500 == 0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
            
    return params

In [13]:
training_loop(
    n_epochs = 5000, 
    learning_rate = 1e-2, 
    params = torch.tensor([1.0, 0.0], requires_grad=True), # <1> 
    t_u = t_un, # <2> 
    t_c = t_c)

Epoch 500, Loss 7.860115
Epoch 1000, Loss 3.828538
Epoch 1500, Loss 3.092191
Epoch 2000, Loss 2.957698
Epoch 2500, Loss 2.933134
Epoch 3000, Loss 2.928648
Epoch 3500, Loss 2.927830
Epoch 4000, Loss 2.927679
Epoch 4500, Loss 2.927652
Epoch 5000, Loss 2.927647


tensor([  5.3671, -17.3012], requires_grad=True)